name: Release new version

on:
  push:
    branches:
      tags:
        - "v*.*.*"

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.2

      - name: Build Binary
        run: go build -o ./tp . && tar -czf tp.tar.gz ./tp

      - name: Create Release
        uses: softprops/action-gh-release@v2
