name: Release new version

on: push

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.2

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y libpcap0.8-dev

      - name: Build Binary for linux/amd64
        run: CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o ./tp-linux-amd64 . && tar -czf tp-linux-amd64.tar.gz ./tp-linux-amd64

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: tp-linux-amd64.tar.gz
